clear; clc;

%% ===== Parameters =====
% These thresholds must match S5_null_model_LNM_generate.m.
LOWER_PERCENTILE = 30;
UPPER_PERCENTILE = 70;

%% ===== Project paths =====

script_dir = fileparts(mfilename('fullpath'));
project_dir = fileparts(script_dir);
project_output_dir = fullfile(project_dir, 'output');

input_dir = fullfile( ...
    project_output_dir, 'R0_true_lesion_r_maps_from_meanFC');
input_pattern = 'Amnesia_rmap_meanFC_*.mat';

output_dir = fullfile( ...
    project_output_dir, 'R1_true_lesion_rLNM_map_results');
output_file = fullfile(output_dir, 'Amnesia_LNM_rmap_30.mat');

%% ===== Find the lesion r-map files generated by S1 =====
if ~exist(input_dir, 'dir')
    error('S1 output directory not found: %s', input_dir);
end

files = dir(fullfile(input_dir, input_pattern));
num_files = numel(files);

if num_files == 0
    error('No files matching "%s" were found in: %s', ...
        input_pattern, input_dir);
end

% Use a consistent processing order.
[~, sort_order] = sort({files.name});
files = files(sort_order);

fprintf('Found %d lesion r-map files in:\n%s\n', num_files, input_dir);

%% ===== Read all lesion r-maps =====
% Determine the r-map length from the first file instead of hard-coding it.
first_r_map = load_r_map(fullfile(input_dir, files(1).name));
num_voxels = numel(first_r_map);

R = zeros(num_voxels, num_files);
R(:, 1) = first_r_map(:);

for j = 2:num_files
    file_path = fullfile(input_dir, files(j).name);
    r_map = load_r_map(file_path);

    if numel(r_map) ~= num_voxels
        error(['R-map length mismatch in "%s": expected %d values, ' ...
            'but found %d.'], files(j).name, num_voxels, numel(r_map));
    end

    R(:, j) = r_map(:);
end

fprintf('Loaded r-map matrix. Size = %d voxels x %d lesions.\n', ...
    num_voxels, num_files);

%% ===== Select the top and bottom percent for each lesion =====
masks = zeros(num_voxels, num_files, 'int8');

for j = 1:num_files
    current_r_map = R(:, j);

    upper_threshold = prctile( ...
        current_r_map, UPPER_PERCENTILE);
    lower_threshold = prctile( ...
        current_r_map, LOWER_PERCENTILE);

    masks(current_r_map >= upper_threshold, j) = 1;
    masks(current_r_map <= lower_threshold, j) = -1;
end

%% ===== Determine the positive or negative majority at each voxel =====
positive_count = sum(masks == 1, 2);
negative_count = sum(masks == -1, 2);
majority_difference = positive_count - negative_count;

majority_count = zeros(num_voxels, 1);

positive_majority = majority_difference > 0;
negative_majority = majority_difference < 0;

majority_count(positive_majority) = positive_count(positive_majority);
majority_count(negative_majority) = -negative_count(negative_majority);

%% ===== Calculate the signed overlap ratio =====
% Positive values indicate a positive-connectivity majority.
% Negative values indicate a negative-connectivity majority.
% Zero indicates a tie or no majority.
overlap = majority_count / num_files;

%% ===== Save the result =====
if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

save(output_file, 'overlap');

fprintf('Saved the signed overlap map to:\n%s\n', output_file);

%% ===== Local function =====
function r_map = load_r_map(file_path)
    file_data = load(file_path);

    if isfield(file_data, 'lesion_r_map')
        r_map = file_data.lesion_r_map;
    elseif isfield(file_data, 'r_values')
        r_map = file_data.r_values;
    else
        error('Neither "lesion_r_map" nor "r_values" was found in: %s', ...
            file_path);
    end

    if ~isnumeric(r_map) || isempty(r_map) || ~isvector(r_map)
        error('The r-map must be a nonempty numeric vector: %s', file_path);
    end

    r_map = double(r_map(:));

    if any(~isfinite(r_map))
        warning('Non-finite values in "%s" were replaced with zero.', ...
            file_path);
        r_map(~isfinite(r_map)) = 0;
    end
end
