clear; clc;

%% ===== Parameters =====
N_NULL = 10000;
Q_THRESHOLD = 0.0001;

% Select the S5 null-model source:
%   'annealing'  - frequency-matched null models
%   'reposition' - randomly repositioned null models
NULL_MODEL_METHOD = 'annealing';

% Stop if the number of null result files is not exactly N_NULL.
REQUIRE_COMPLETE_NULL_SET = true;

%% ===== Project paths =====
script_dir = fileparts(mfilename('fullpath'));
project_dir = fileparts(script_dir);
project_output_dir = fullfile(project_dir, 'output');

true_overlap_file = fullfile( ...
    project_output_dir, ...
    'R1_true_lesion_rLNM_map_results', ...
    'Amnesia_LNM_rmap_30.mat');

switch lower(NULL_MODEL_METHOD)
    case 'annealing'
        null_overlap_dir = fullfile( ...
            project_output_dir, ...
            sprintf(['R4_LNM_rmaps_null_%d_results_' ...
            'percent30_sortedfreq'], N_NULL));
        result_dir = fullfile( ...
            project_output_dir, ...
            'R5_Permutation_FDR_results_percent30_sortedfreq');

    case 'reposition'
        null_overlap_dir = fullfile( ...
            project_output_dir, ...
            sprintf(['R4_LNM_rmaps_null_%d_results_' ...
            'percent30_reposition'], N_NULL));
        result_dir = fullfile( ...
            project_output_dir, ...
            'R5_Permutation_FDR_results_percent30_reposition');

    otherwise
        error(['NULL_MODEL_METHOD must be either "annealing" ' ...
            'or "reposition".']);
end

%% ===== Validate parameters and input paths =====
if N_NULL < 1 || N_NULL ~= floor(N_NULL)
    error('N_NULL must be a positive integer.');
end

if Q_THRESHOLD <= 0 || Q_THRESHOLD > 1
    error('Q_THRESHOLD must be greater than 0 and no greater than 1.');
end

if exist('mafdr', 'file') ~= 2
    error(['mafdr was not found. The original S7 calculation requires ' ...
        'the MATLAB Bioinformatics Toolbox.']);
end

if ~isfile(true_overlap_file)
    error('S2 true-overlap file not found: %s', true_overlap_file);
end

if ~exist(null_overlap_dir, 'dir')
    error('S5 null-overlap directory not found: %s', null_overlap_dir);
end

if ~exist(result_dir, 'dir')
    mkdir(result_dir);
end

%% ===== Load the true lesion overlap map from S2 =====
true_file_data = load(true_overlap_file, 'overlap');

if ~isfield(true_file_data, 'overlap')
    error('Variable "overlap" was not found in: %s', true_overlap_file);
end

true_overlap = validate_overlap_vector( ...
    true_file_data.overlap, [], true_overlap_file);
num_voxels = numel(true_overlap);

fprintf('Loaded the true overlap map with %d voxels.\n', num_voxels);

%% ===== Find the null overlap maps generated by S5 =====
null_pattern = 'Amnesia_LNM_rmap_null*.mat';
null_files = dir(fullfile(null_overlap_dir, null_pattern));
num_null = numel(null_files);

if num_null == 0
    error('No null overlap files were found in: %s', null_overlap_dir);
end

% Sort by filename so processing order follows the null model number.
[~, sort_order] = sort({null_files.name});
null_files = null_files(sort_order);

if REQUIRE_COMPLETE_NULL_SET && num_null ~= N_NULL
    error(['Expected exactly %d null overlap files, but found %d in: ' ...
        '%s'], N_NULL, num_null, null_overlap_dir);
elseif num_null ~= N_NULL
    warning('Expected %d null files, but %d available files will be used.', ...
        N_NULL, num_null);
end

fprintf('Found %d null overlap maps.\n', num_null);

%% ===== Voxel-wise directional permutation comparison =====
% This reproduces the original S6 definition:
%   true overlap >= 0: ratio = P(true > null)
%   true overlap <  0: ratio = P(true < null)
%
% Null files are processed one at a time to avoid storing a large
% num_voxels-by-num_null matrix in memory.
less_extreme_count = zeros(num_voxels, 1);

positive_direction = true_overlap >= 0;
negative_direction = true_overlap < 0;

for null_number = 1:num_null
    null_file = fullfile( ...
        null_overlap_dir, null_files(null_number).name);
    null_file_data = load(null_file, 'overlap');

    if ~isfield(null_file_data, 'overlap')
        error('Variable "overlap" was not found in: %s', null_file);
    end

    null_overlap = validate_overlap_vector( ...
        null_file_data.overlap, num_voxels, null_file);

    less_extreme_count(positive_direction) = ...
        less_extreme_count(positive_direction) + ...
        (true_overlap(positive_direction) > ...
        null_overlap(positive_direction));

    less_extreme_count(negative_direction) = ...
        less_extreme_count(negative_direction) + ...
        (true_overlap(negative_direction) < ...
        null_overlap(negative_direction));

    if mod(null_number, 100) == 0 || null_number == num_null
        fprintf('Processed %d / %d null overlap maps.\n', ...
            null_number, num_null);
    end
end

ratio = less_extreme_count / num_null;

%% ===== Convert the permutation ratio to one-sided p-values =====

pval = 1 - ratio;
pval(pval < eps) = eps;
pval(pval > 1) = 1;

%% ===== Benjamini-Hochberg FDR correction =====
pval_vector = pval(:);
qval_vector = mafdr(pval_vector, 'BHFDR', true);
qval = reshape(qval_vector, size(pval));

% 只保留正值体素
positive_voxels = true_overlap > 0;

% 在正值体素中，统计 q < 阈值的个数
significant_mask_all = qval < Q_THRESHOLD;
significant_mask_positive = significant_mask_all & positive_voxels;
num_significant_positive = nnz(significant_mask_positive);
num_positive_total = nnz(positive_voxels);

fprintf('Positive voxels with q < %.6g: %d / %d (%.2f%%)\n', ...
    Q_THRESHOLD, num_significant_positive, num_positive_total, ...
    100 * num_significant_positive / num_positive_total);

true_overlap_masked = zeros(size(true_overlap));  % 非显著位置设为 0
true_overlap_masked(significant_mask_positive) = true_overlap(significant_mask_positive);

%% ===== Save the combined permutation and FDR results =====
result_file = fullfile( ...
    result_dir, ...
    sprintf(['Amnesia_true_vs_null_%05d_percent30_' ...
    'ratio_pval_FDR.mat'], num_null));

save(result_file, ...
    'ratio', ...
    'pval', ...
    'qval', ...
    'true_overlap_masked', ... 
    'significant_mask_positive', ... 
    'Q_THRESHOLD', ... 
    'NULL_MODEL_METHOD', ...
    '-v7.3');

fprintf('Permutation and FDR results saved to:\n%s\n', result_file);

%% ===== Local functions =====
function overlap = validate_overlap_vector( ...
        overlap_input, expected_length, source_file)

    if ~isnumeric(overlap_input) || isempty(overlap_input) || ...
            ~isvector(overlap_input)
        error('Variable "overlap" must be a nonempty numeric vector: %s', ...
            source_file);
    end

    overlap = double(overlap_input(:));

    if ~isempty(expected_length) && numel(overlap) ~= expected_length
        error(['Overlap length mismatch in "%s": expected %d values, ' ...
            'but found %d.'], ...
            source_file, expected_length, numel(overlap));
    end

    if any(~isfinite(overlap))
        error('Variable "overlap" contains non-finite values: %s', ...
            source_file);
    end
end
